### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Ravindra-Raut** [davedgd/ggNestedBarChart#1]
I got the following error after running the command:
install.packages("remotes")
remotes::install_github("davedgd/ggNestedBarChart")

OUTPUT:
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘data.table’ in library.dynam(lib, package, package.lib):
 shared object ‘datatable.so’ not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/data.table’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/data.table’
Error: Failed to install 'ggNestedBarChart' from GitHub:
  (converted from warning) installation of package ‘data.table’ had non-zero exit status

**Comment by davedgd** [comment]
Ah, I see the issue. There's a new release of the data.table package that requires a source compile since binary versions aren't widely available yet. To resolve this, try the following:

```
install.packages("data.table", type = "binary")
install.packages("devtools") # or use remotes here and below
devtools::install_github("davedgd/ggNestedBarChart")
```

You may still get a message about updating packages that have "more recent versions available"; if you do, go with "None" when asked which ones to update, similar to below (i.e., choice 3 in the screenshot below):

![issue](https://user-images.githubusercontent.com/4490587/88483974-44a57100-cf39-11ea-91df-90b665fb6a1a.png)

This should resolve the issue, which unfortunately seems to be about source compilations rather than something I can directly fix. By the by, ensuring all the various R tools are installed as described in the links below may be another way of resolving the issue more directly:

[Windows](https://cran.r-project.org/bin/windows/Rtools/)
[Mac](https://mac.r-project.org/tools/)

Hopefully this helps!

**Comment by davedgd** [comment]
I'm hoping this issue is fixed, but please let me know if not; closing for now!
